spring:
  application:
    name: cartoes-microservice
  datasource:
    url: ${DB_URL:jdbc:h2:mem:cartoesdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER_CLASS_NAME:org.h2.Driver}
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
      path: ${H2_CONSOLE_PATH:/h2-console}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

app:
  rabbitmq:
    exchange: ${CARTAO_EXCHANGE:cartoes.exchange}
    criado-queue: ${CARTAO_CRIADO_QUEUE:cartoes.criados.queue}
    ativado-queue: ${CARTAO_ATIVADO_QUEUE:cartoes.ativados.queue}
    cancelado-queue: ${CARTAO_CANCELADO_QUEUE:cartoes.cancelados.queue}
    criado-routing-key: ${CARTAO_CRIADO_ROUTING_KEY:cartao.criado}
    ativado-routing-key: ${CARTAO_ATIVADO_ROUTING_KEY:cartao.ativado}
    cancelado-routing-key: ${CARTAO_CANCELADO_ROUTING_KEY:cartao.cancelado}

springdoc:
  swagger-ui:
    path: /swagger-ui.html